spring:
  application:
    name: answer

  datasource:
    username: root
    password: Cs@123456
    url: jdbc:mysql://rm-bp1e42in3hei8loadgo.mysql.rds.aliyuncs.com:3306/answer?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&verifyServerCertificate=false&zeroDateTimeBehavior=CONVERT_TO_NULL
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    #配置静态文件访问
    static-path-pattern: /static/**

server:
  port: 8001
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /answer

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
